config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :customers
  resources :users
  resources :departaments
  resources :categories
  resources :mytickets
  resources :comments

  root 'mytickets#index'

end

app/models/myticket.rb
class Myticket < ActiveRecord::Base
  belongs_to :customer, class_name: 'User', foreign_key: 'id_customer'
	belongs_to :departament
	belongs_to :category

  has_many :comments

 	mount_uploader :upload, UploadUploader
	# validates :subject, :departament, :category, :mensage, :upload, :status, presence: true

  enum status: { Aberto: '0', Aguardando: '1', Finalizado: '2', Cancelado: '3' }

  before_create :set_active_status

  def set_active_status
    self.status = Myticket.statuses[:active]
  end

  def self.search(search)
    if search
      find(:all, :conditions => ['subject LIKE ? OR category LIKE', "%#{search}"])
    else
      all
    end
  end

end

app/controllers/mytickets_controller.rb
class MyticketsController < ApplicationController
  before_action :set_myticket, only: [:show, :edit, :update, :destroy]

  # GET /mytickets
  # GET /mytickets.json
  def index
    @mytickets = current_user.admin? ? Myticket.all : current_user.mytickets
    @mytickets = Myticket.search(params[:search])
  end

  # GET /mytickets/1
  # GET /mytickets/1.json
  def show
  end

  # GET /mytickets/new
  def new
    @myticket = Myticket.new
  end

  # GET /mytickets/1/edit
  def edit
  end

  # POST /mytickets
  # POST /mytickets.json
  def create
    @myticket = Myticket.new(myticket_params)
    @myticket.customer = current_user

    respond_to do |format|
      if @myticket.save
        format.html { redirect_to @myticket, notice: 'Myticket was successfully created.' }
        format.json { render :show, status: :created, location: @myticket }
      else
        format.html { render :new }
        format.json { render json: @myticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mytickets/1
  # PATCH/PUT /mytickets/1.json
  def update
    respond_to do |format|
      if @myticket.update(myticket_params)
        format.html { redirect_to @myticket, notice: 'Myticket was successfully updated.' }
        format.json { render :show, status: :ok, location: @myticket }
      else
        format.html { render :edit }
        format.json { render json: @myticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mytickets/1
  # DELETE /mytickets/1.json
  def destroy
    @myticket.destroy
    respond_to do |format|
      format.html { redirect_to mytickets_url, notice: 'Myticket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_myticket
      @myticket = Myticket.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def myticket_params
      params.require(:myticket).permit(:id_customer, :subject, :mensage, :upload, :status, :date, :deadline)
    end

end

app/helpers/mytickets_helper.rb
module MyticketsHelper
  def status_label(myticket)
    (myticket.status == 'Aberto') ?
      'success' :
      ((myticket.status == 'Aguardando') ?
        'warning' :
        (myticket.status == 'Finalizado') ?
          'default' :
        'danger')
  end
end

app/views/mytickets/_form.html.erb
<%= form_for @myticket, :html => { :class => "form-horizontal myticket" } do |f| %>

    <% if @myticket.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@myticket.errors.count, "error") %> prohibited this myticket from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @myticket.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :subject, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :subject, :class => 'form-control' %>
    </div>
    <%= error_span(@myticket[:subject]) %>
  </div>
  <div class="control-group">
    <%= f.label :departament, :class => 'control-label' %>
    <div class="controls">
    <%= f.select :departament_id, Departament.all.map {|i| [i.title, i.id] }, :class => 'form-control' %>
    </div>
    <%= error_span(@myticket[:departament]) %>
  </div>
  <div class="control-group">
    <%= f.label :category, :class => 'control-label' %>
    <div class="controls">
    <%= f.select :category_id, Category.all.map {|i| [i.name, i.id] }, :class => 'form-control' %>
    </div>
    <%= error_span(@myticket[:categories]) %>
  </div>
  <div class="control-group">
    <%= f.label :mensage, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :mensage, :class => 'form-control' %>
    </div>
    <%= error_span(@myticket[:mensage]) %>
  </div>
  <div class="control-group">
    <%= f.label :upload, :class => 'control-label' %>
    <div class="controls">
      <%= f.file_field :upload, :class => 'form-control' %>
    </div>
    <%= error_span(@myticket[:upload]) %>
  </div>

  <% unless current_user.client? %>
    <div class="control-group">
      <%= f.label :status, :class => 'control-label' %>
      <div class="controls">
        <%= f.select :status, Myticket.statuses, :class => 'form-control' %>
      </div>
      <%= error_span(@myticket[:categories]) %>
    </div>
  <% end %>

  <br/>
  <div class="control-group">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
              mytickets_path, :class => 'btn btn-default' %>
  </div>

<% end %>

app/views/mytickets/edit.html.erb
<%- model_class = Myticket -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/mytickets/index.html.erb
<div class="col-sm-6 col-md-5 col-lg-6">
  <div>
    <h1>Chamados</h1>
    <p class="lead">Acompanhe os seus chamados junto à DM11.</p>
  </div>
</div>

<div style="padding: 30px 15px" class="col-sm-6 col-md-5 col-lg-6">
    <input class="form-control input-lg" type="text" placeholder="Buscar chamado...">

    <% form_tag mytickets_path, :method => 'get' do %>
      <% text_field_tag :search, params[:search] %>
      <%= submit_tag "Search", :name => nil %>
    <% end %>
</div>

<div class="row"></div>

<hr>

<ul id="tickets-status-filter" class="nav nav-tabs" role="tablist">
  <li role="presentation" class="active">
    <a href="#status-all">Todos os Chamados <span class="badge">42</span></a>
  </li>
  <li role="presentation">
    <a href="#status-opened">Chamados Abertos <span class="badge">10</span></a>
  </li>
  <li role="presentation">
    <a href="#status-closed">Chamados Finalizados <span class="badge">30</span></a>
  </li>
  <li role="presentation">
    <a href="#status-canceled">Chamados Cancelados <span class="badge">2</span></a>
  </li>
  <li class="pull-right" role="presentation">
    <%= link_to t('.new', :default => t("helpers.links.new")), new_myticket_path, :class => "btn btn-primary", data: {toggle: "modal", garget: "#abrirchamado"}  %>
  </li>
</ul>

<div class="tab-content">
  <table id="status-all" class="table table-striped tab-pane active" role="tabpanel">
    <thead>
      <tr>
        <th>Chamado</th>
        <th>Assunto</th>
        <th>Data</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @mytickets.each do |myticket| %>
        <tr>
          <td><%= link_to "#%06d" % myticket.id, myticket_path(myticket) %></td>
          <td><%= myticket.subject %> <span class="label label-<%= status_label(myticket) %>"><%= myticket.status %></span></td>
          <td><%=l myticket.created_at %></td>
          <td>
            <%= link_to 'Visualizar', myticket_path(myticket), :class => 'btn btn-info btn-xs' %>
            <%= link_to t('.edit', :default => t("helpers.links.edit")),
                        edit_myticket_path(myticket), :class => 'btn btn-warning btn-xs' %>
            <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                        myticket_path(myticket),
                        :method => :delete,
                        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                        :class => 'btn btn-xs btn-danger' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <table id="status-opened" class="table table-striped tab-pane" role="tabpanel">
    <thead>
      <tr>
        <th>Chamado</th>
        <th>Assunto</th>
        <th>Data</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @mytickets.take(2).each do |myticket| %>
        <tr>
          <td><%= link_to "#%06d" % myticket.id, myticket_path(myticket) %></td>
          <td><%= myticket.subject %> <span class="label label-<%= status_label(myticket) %>"><%= myticket.status %></span></td>
          <td><%=l myticket.created_at %></td>
          <td>
            <%= link_to 'Visualizar', myticket_path(myticket), :class => 'btn btn-info btn-xs' %>
            <%= link_to t('.edit', :default => t("helpers.links.edit")),
                        edit_myticket_path(myticket), :class => 'btn btn-warning btn-xs' %>
            <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                        myticket_path(myticket),
                        :method => :delete,
                        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                        :class => 'btn btn-xs btn-danger' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/mytickets/new.html.erb
<%- model_class = Myticket -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/mytickets/show.html.erb
<%- model_class = Myticket -%>

<div class="row page-header">
      <h1 class="lead pull-left"><%= @myticket.subject %> <span class="text-uppercase label label-<%= status_label(@myticket) %>"><%= @myticket.status %></span></h1>
      <%= link_to t('.back', :default => t("helpers.links.back")),
                    mytickets_path, :class => 'btn btn-info btn-lg pull-right'  %>
</div>

<div class="row">
  <div class="col-md-4">
    <blockquote>
      <strong>Chamado <%= "#%06d" % @myticket.id %></strong>
    </blockquote>
  </div>
  <div class="col-md-4">
      <strong>Status: </strong><%= @myticket.status %><br>
      <strong>Data de abertura: </strong><%=l @myticket.created_at %><br>
  </div>
  <div class="col-md-4">
      <strong>Seu nome: </strong>Nome do Cliente<br>
      <strong>Seu telefone: </strong>Telefone do Cliente<br>
      <strong>Email para contato: </strong>Email do cliente
  </div>
</div>

<hr>
<div class="row">
  <div class="col-md-12 jumbotron">
    <h4>Descrição:</h4>
    <p class="text-justify">
      <%= @myticket.mensage %>
    </p>
  </div>
</div>

<div class="row">
  <div class="alert alert-warning"><strong>Como esta o meu atendimento?</strong>
  Entre em contato com o meu coordenador para qualquer feedback, enviando uma mensagem com assunto:<br>
  <strong><%= @myticket.subject %> - <%= "#%06d" % @myticket.id %></strong>, através do email <a class="alert-link" href="mailto:suporte@dm11.com.br">suporte@dm11.com.br</a>.
  </div>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:id_customer) %>:</strong></dt>
  <dd><%= @myticket.customer.try(:email) %></dd>
  <dt><strong><%= model_class.human_attribute_name(:subject) %>:</strong></dt>
  <dd><%= @myticket.subject %></dd>
  <dt><strong><%= model_class.human_attribute_name(:departament) %>:</strong></dt>
  <dd><%= @myticket.departament %></dd>
  <dt><strong><%= model_class.human_attribute_name(:category) %>:</strong></dt>
  <dd><%= @myticket.category %></dd>
  <dt><strong><%= model_class.human_attribute_name(:mensage) %>:</strong></dt>
  <dd><%= @myticket.mensage %></dd>
  <dt><strong><%= model_class.human_attribute_name(:upload) %>:</strong></dt>
  <dd><%= @myticket.upload %></dd>
  <dt><strong><%= model_class.human_attribute_name(:status) %>:</strong></dt>
  <dd><%= @myticket.status %></dd>
  <dt><strong><%= model_class.human_attribute_name(:deadline) %>:</strong></dt>
  <dd><%= @myticket.deadline %></dd>
</dl>

<% @myticket.comments.each do |comment| %>
  <p>
    <%= comment.description %> - <%= comment.user.name %>
  </p>
<% end %>

<%= form_for @myticket.comments.build do |f| %>
  <%= f.text_area :description %>
  <%= f.submit %>
<% end %>

<%= link_to t('.back', :default => t("helpers.links.back")),
              mytickets_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_myticket_path(@myticket), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              myticket_path(@myticket),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>