config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :customers
  resources :users
  resources :departaments
  resources :categories
  resources :mytickets
  resources :comments

  root 'mytickets#index'

end

app/models/customer.rb
class Customer < ActiveRecord::Base
	validates :emails, :name, :phone, :address, :cpf_cnpj, presence: true
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :only_admin
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:name, :emails, :phone, :address, :cpf_cnpj, :logo, :website, :facebook, :customer_since)
    end
end

app/views/customers/_form.html.erb
<%= form_for @customer, :html => { :class => "form-horizontal customer" } do |f| %>

    <% if @customer.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @customer.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%= error_span(@customer[:name]) %>
  </div>
  <div class="control-group">
    <%= f.label :emails, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :emails, :class => 'form-control' %>
    </div>
    <%= error_span(@customer[:emails]) %>
  </div>
  <div class="control-group">
    <%= f.label :phone, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :phone, :class => 'form-control' %>
    </div>
    <%= error_span(@customer[:phone]) %>
  </div>
  <div class="control-group">
    <%= f.label :address, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :address, :class => 'form-control' %>
    </div>
    <%= error_span(@customer[:address]) %>
  </div>
  <div class="control-group">
    <%= f.label :cpf_cnpj, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :cpf_cnpj, :class => 'form-control' %>
    </div>
    <%= error_span(@customer[:cpf_cnpj]) %>
  </div>
  <div class="control-group">
    <%= f.label :logo, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :logo, :class => 'form-control' %>
    </div>
    <%= error_span(@customer[:logo]) %>
  </div>
  <div class="control-group">
    <%= f.label :website, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :website, :class => 'form-control' %>
    </div>
    <%= error_span(@customer[:website]) %>
  </div>
  <div class="control-group">
    <%= f.label :facebook, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :facebook, :class => 'form-control' %>
    </div>
    <%= error_span(@customer[:facebook]) %>
  </div>
  <div class="control-group">
    <%= f.label :customer_since, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :customer_since, :class => 'form-control' %>
    </div>
    <%= error_span(@customer[:customer_since]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            customers_path, :class => 'btn btn-default' %>

<% end %>

app/views/customers/edit.html.erb
<%- model_class = Customer -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/customers/index.html.erb
<%- model_class = Customer -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:emails) %></th>
      <th><%= model_class.human_attribute_name(:phone) %></th>
      <th><%= model_class.human_attribute_name(:cpf_cnpj) %></th>
    </tr>
  </thead>
  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= link_to customer.name, customer_path(customer) %></td>
        <td><%= customer.emails %></td>
        <td><%= customer.phone %></td>
        <td><%= customer.cpf_cnpj %></td>
        <td>
          <%= link_to 'Visualizar', customer_path(customer), :class => 'btn btn-info btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_customer_path(customer), :class => 'btn btn-warning btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      customer_path(customer),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_customer_path,
            :class => 'btn btn-primary' %>

app/views/customers/new.html.erb
<%- model_class = Customer -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/customers/show.html.erb
<%- model_class = Customer -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @customer.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:emails) %>:</strong></dt>
  <dd><%= @customer.emails %></dd>
  <dt><strong><%= model_class.human_attribute_name(:phone) %>:</strong></dt>
  <dd><%= @customer.phone %></dd>
  <dt><strong><%= model_class.human_attribute_name(:address) %>:</strong></dt>
  <dd><%= @customer.address %></dd>
  <dt><strong><%= model_class.human_attribute_name(:cpf_cnpj) %>:</strong></dt>
  <dd><%= @customer.cpf_cnpj %></dd>
  <dt><strong><%= model_class.human_attribute_name(:logo) %>:</strong></dt>
  <dd><%= @customer.logo %></dd>
  <dt><strong><%= model_class.human_attribute_name(:website) %>:</strong></dt>
  <dd><%= @customer.website %></dd>
  <dt><strong><%= model_class.human_attribute_name(:facebook) %>:</strong></dt>
  <dd><%= @customer.facebook %></dd>
  <dt><strong><%= model_class.human_attribute_name(:customer_since) %>:</strong></dt>
  <dd><%= @customer.customer_since %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              customers_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_customer_path(@customer), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              customer_path(@customer),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>