config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :customers
  resources :users
  resources :departaments
  resources :categories
  resources :mytickets
  resources :comments

  root 'mytickets#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Ticket" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
    <link href="css/bootstrap.css" rel="stylesheet">
    <link href="css/bootstrap-theme.css" rel="stylesheet">
    <script src="js/ie-emulation-modes-warning.js"></script>
  </head>
  <body>
  <% if signed_in? %>
    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
          <a class="navbar-brand" href="#">
            <strong>DM11</strong> | Central do Cliente
          </a>        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li class="<%= current_page?(mytickets_path) ? 'active' : '' %>"><%= link_to 'Chamados
            <span class="sr-only">(current)</span>'.html_safe, mytickets_path %></li>

            <li class="<%= current_page?(categories_path) ? 'active' : '' %>"><%= link_to 'Categorias
            <span class="sr-only">(current)</span>'.html_safe, categories_path %></li>

            <li class="<%= current_page?(departaments_path) ? 'active' : '' %>"><%= link_to 'Departamentos
            <span class="sr-only">(current)</span>'.html_safe, departaments_path %></li>

            <li class="<%= current_page?(users_path) ? 'active' : '' %>"><%= link_to 'Usuários
            <span class="sr-only">(current)</span>'.html_safe, users_path %></li>

            <li class="<%= current_page?(customers_path) ? 'active' : '' %>"><%= link_to 'Clientes
            <span class="sr-only">(current)</span>'.html_safe, customers_path %></li>

            <li><a href="#">Relatórios</a></li>
          </ul>

          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li><%= link_to current_user.email .html_safe, user_path(current_user) %></li>
                <li class="pull-right">
                  <%= link_to('Sair', destroy_user_session_path, method: :delete) %>
                </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
    <% end %>
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <!-- INÍCIO SIDEBAR
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div>
        </div>
       FIM SIDEBAR -->
      </div><!--/row-->
      <footer class="text-center">
        <p style="color: #777">- TickET &copy; 2015 -</p>
      </footer>

    </div> <!-- /container -->

    <script src="js/ie10-viewport-bug-workaround.js"></script>
    <script src="js/bootstrap-min.js"></script>
    <script src="js/npm.js"></script>
    <script src="js/modal.js"></script>
    <script src="js/collapse.js"></script>
    <script src="js/dropdown.js"></script>
  </body>
</html>